# Linear Algebra

The NumPy package probably offers the most straightforward way to use linear algebra.

As we mentioned before, it gives you the option of defining numerical arrays and matrices. The main difference between an array and a matrix is this:

**Multiplication**:
 - For a *NumPy array*, `*` performs element-wise multiplication, and `@` performs matrix multiplication (for Python $\geq$3.5. `numpy.dot()` works with all versions of Python and does the same thing.)
 - For a *NumPy matrix*, `*` performs matrix multiplication. If you want element-wise multiplication, you should use `numpy.multiply()`.
 - `numpy.dot()` performs matrix multiplication for both matrices and arrays, and `numpy.multiply()` performs element-wise multiplication for both.

**Matrix power**:
 - For a *NumPy array*, `**` performs element-wise exponentiation, and `numpy.linalg.matrix_power()` calculates the matrix power.
 - For a *NumPy matrix*, `**` calculates the matrix power, while `numpy.power()` raises each element to a power.
 - `numpy.linalg.matrix_power()` and `numpy.power()` each have the same effect on each type.

Let's try it out:

In [1]:
import numpy as np


A_array = np.array([[1,2,3],
                     [2,3,1],
                     [2,1,3]
                    ])


print('Multiplication:')
print('')

print('array, with `*` operator')
print(A_array*A_array)
print('')

print('array, with `@` operator')
print(A_array@A_array)
print('')

print('array, `numpy.multiply`')
print(np.multiply(A_array,A_array))
print('')

print('array, `numpy.dot`')
print(np.dot(A_array,A_array))
print('')

print('Powers:')
print('')

print('array, with `**` operator')
print(A_array**2)
print('')


print('array, with `numpy.linalg.matrix_power`')
print(np.linalg.matrix_power(A_array,2))
print('')


Multiplication:

array, with `*` operator
[[1 4 9]
 [4 9 1]
 [4 1 9]]

array, with `@` operator
[[11 11 14]
 [10 14 12]
 [10 10 16]]

array, `numpy.multiply`
[[1 4 9]
 [4 9 1]
 [4 1 9]]

array, `numpy.dot`
[[11 11 14]
 [10 14 12]
 [10 10 16]]

Powers:

array, with `**` operator
[[1 4 9]
 [4 9 1]
 [4 1 9]]

array, with `numpy.linalg.matrix_power`
[[11 11 14]
 [10 14 12]
 [10 10 16]]



In [2]:
import numpy as np

A_matrix = np.matrix([[1,2,3],
                     [2,3,1],
                     [2,1,3]
                    ])


print('Multiplication:')
print('')

print('matrix, with `*` operator')
print(A_matrix*A_matrix)
print('')

print('matrix, with `@` operator')
print(A_matrix@A_matrix)
print('')

print('matrix, `numpy.multiply`')
print(np.multiply(A_matrix,A_matrix))
print('')

print('matrix, `numpy.dot`')
print(np.dot(A_matrix,A_matrix))
print('')



print('Powers:')
print('')

print('matrix, with `**` operator')
print(A_matrix**2)
print('')


print('matrix, with `numpy.power`')
print(np.power(A_matrix,2))
print('')


Multiplication:

matrix, with `*` operator
[[11 11 14]
 [10 14 12]
 [10 10 16]]

matrix, with `@` operator
[[11 11 14]
 [10 14 12]
 [10 10 16]]

matrix, `numpy.multiply`
[[1 4 9]
 [4 9 1]
 [4 1 9]]

matrix, `numpy.dot`
[[11 11 14]
 [10 14 12]
 [10 10 16]]

Powers:

matrix, with `**` operator
[[11 11 14]
 [10 14 12]
 [10 10 16]]

matrix, with `numpy.power`
[[1 4 9]
 [4 9 1]
 [4 1 9]]



## Other simple linear algebra operations

Both array and matrices can be transposed using the same methods: either `.T` or `.transpose()` or `numpy.transpose()`. For example:

In [3]:
print(A_array.T)

print(A_array.transpose())

print(np.transpose(A_matrix))

[[1 2 2]
 [2 3 1]
 [3 1 3]]
[[1 2 2]
 [2 3 1]
 [3 1 3]]
[[1 2 2]
 [2 3 1]
 [3 1 3]]


The determinant can be computed using the `numpy.linalg.det()` function:

In [4]:
np.linalg.det(A_array)

-12.0

This matrix has a non-zero determinant, which should mean that it's invertible. Let's check:

In [5]:
A_matrix**(-1)

matrix([[-0.66666667,  0.25      ,  0.58333333],
        [ 0.33333333,  0.25      , -0.41666667],
        [ 0.33333333, -0.25      ,  0.08333333]])

## Solving systems of linear equations

Consider the following non-homogeneous system of equations:

$$ \mathbf{A} \phi = \mathbf{b},$$

where

$$
\begin{align}
\underset{3 \times 3}{\mathbf{A}} &= \begin{bmatrix} 
a_{11} & a_{12} & a_{13} \\
a_{21} & a_{22} & a_{23} \\
a_{31} & a_{32} & a_{33} 
\end{bmatrix},\\\\
\underset{3\times 1}{\mathbf{b}} &= \begin{bmatrix} 
b_{1}  \\
b_{2}  \\
b_{3} 
\end{bmatrix},\\\\
\underset{3\times 1}{\phi} &= \begin{bmatrix} \phi_1 \\ \phi_2 \\ \phi_3 \end{bmatrix}
\end{align}
$$

Suppose that the values of the elements of $\mathbf{A}$ and $\mathbf{b}$ are given, and you want to solve for $\phi$.

The closed-form characterization of the solution for $\phi$ is given by:

$$ \begin{align}\mathbf{A}^{-1} \mathbf{A} \phi &= \mathbf{A}^{-1}\mathbf{b} \\
\\
\phi &= \mathbf{A}^{-1}\mathbf{b}\end{align}$$

There are at least two ways to compute this result:
  1. Compute $\mathbf{A}^{-1}$, then multiply the result by $\mathbf{b}$.
  2. Use a linear equation solver such as `numpy.linalg.lstsq()`, which will *implicitly* invert $\mathbf{A}$ as part of the algorithm which produces the solution (but which will only return the solution and not the inverse of $\mathbf{A}$).

Option (2) is usually preferred because it is less prone to numerical errors. The reason is that if you compute the inverse separately first, as in Option (1), in some instances there will be substantial numerical errors in the calculations. These errors will then get compounded if you store the values with the errors and then perform a whole new set of calculations for the matrix multiplication.

On the other hand, Option (2) involves a smaller number of calculations overall and does not store the result of the inverse mid-way, and so will often but subject to less numerical error.

In many cases where the matrix is not "ill-conditioned" and thus calculating the inverse is subject to less numerical error, the two methods will produce nearly identical results.

Below we can see an example.

In [12]:
A = np.matrix([[1,2,3],
             [2,3,1],
             [2,1,3]
            ])

b = np.matrix([[4],[5],[6]])

phi_estimate_1 = (A**(-1))*b
phi_estimate_2 = np.linalg.lstsq(A,b)[0]

print(phi_estimate_1)

print(phi_estimate_2)

[[2.08333333]
 [0.08333333]
 [0.58333333]]
[[2.08333333]
 [0.08333333]
 [0.58333333]]


C:\Users\MDelventhal\AppData\Local\Temp\ipykernel_264\396329720.py:9: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  phi_estimate_2 = np.linalg.lstsq(A,b)[0]


## Matrix conditioning

A matrix that is "less than full rank" or "singular" has one or more columns that can be represented as a linear combination of other columns.

It always has a determinant of 0. It cannot be inverted. Trying to invert a singular matrix is a bit like trying to divide by 0!

A matrix that is "ill-conditioned" has one or more columns that could *almost* be represented as a linear combination of others, ***but not quite***. One sign of such a matrix is that its determinant will be *close to zero*. It *can* be inverted, *in principle.* In practice, the algorithms we have available to invert such matrices will sometimes produce very large errors.

Take the matrix $\mathbf{A}$ from our example above. Let's use the `numpy.linalg.det()` function to compute its determinant:

In [13]:
np.linalg.det(A)

-12.0

A determinant of -12 is a nice, healthy number far away from 0. There should be no significant numerical problems inverting this matrix. Indeed we see in the example above, our two methods for solving the system of equations yield apparently identical results.

Now, let's try a different matrix $\mathbf{D}$:

In [14]:
D = np.matrix([[1,2,3],
             [1,2,3],
             [1,2,3]
            ])
np.linalg.det(D)

0.0

The columns of $\mathbf{D}$ are not just linearly dependent, they are identical! Of course its determinant is zero. Attempting to invert it will return an error.

How above this next matrix, $\mathbf{G}$?

In [16]:
G = np.matrix([[1,2,3],
             [1.1,2.1,2.9],
             [0.9,1.9,3.1]
            ])
np.linalg.det(G)

8.881784197001204e-17

The values of $\mathbf{G}$ are very close to the values of the singular matrix $\mathbf{D}$, but they have been shifted a little up or down so that they are not *quite* collinear any more. But the *almost* are. that's why the determinant is very close to zero.

Now let's try to solve the following system of equations:

$$ \mathbf{G} \phi = \mathbf{b}$$

### Quick exercise for matrix conditioning:

In the dell below, try finding the solution for $\phi$ in the above system using both the methods we tried before. Are the two results similar? If they're different, which one do you trust more?

In [23]:
print((G**(-1))*G)


phi_estimate_1 = (G**(-1))*b
phi_estimate_2 = np.linalg.lstsq(G,b)[0]

print(phi_estimate_1)
print(phi_estimate_2)

print(G*phi_estimate_1)

print(G*phi_estimate_2)

[[ 3.175   6.8     8.2   ]
 [ 0.     -1.     -2.    ]
 [-0.0125  0.6125  1.2625]]
[[-1.68884986e+16]
 [ 1.35107989e+16]
 [-3.37769972e+15]]
[[-1.30952381]
 [-0.95238095]
 [ 2.73809524]]
[[15. ]
 [14.2]
 [13.8]]
[[5. ]
 [4.5]
 [5.5]]


C:\Users\MDelventhal\AppData\Local\Temp\ipykernel_264\2909496062.py:5: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  phi_estimate_2 = np.linalg.lstsq(G,b)[0]


## Eigenvalues

Consider the following geometric sequence:

$$\left \{\beta^i \right \}_{i=0}^{\infty}$$

How can be tell whether or not the sequence will converge, and $\lim\limits_{i\to\infty} \beta^i = 0$?

The rule is simple once you know it--we'll have convergence for $\beta \in (-1,1)$.

Now, what about this next sequence:

$$ \left \{ \mathbf{B}^i \right \}_{i=0}^{\infty},$$

for $$ \underset{m \times n}{\mathbf{B}} = \begin{bmatrix} 
b_{11} & b_{12} & \dots & b_{1n}\\
b_{21} & b_{22} & \dots & b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
b_{n1} & b_{n2} & \dots & b_{nn}
\end{bmatrix}$$


What will $\lim\limits_{i \to \infty} \mathbf{B}^i$ be? And how can we know whether it will converge?

It turns out, that if the sequence converges, $$\lim\limits_{i \to \infty} \mathbf{B}^i = \underset{n \times n}{\mathbf{0}} = \begin{bmatrix} 
0 & 0 & \dots & 0\\
0 & 0 & \dots & 0 \\
\vdots & \vdots & \ddots & \vdots \\
0 & 0 & \dots & 0
\end{bmatrix}.$$

How can we know whether this will occur?

The answer turns out to be: It depends on whether the magnitude of the largest eigenvalue of the matrix is bounded strictly between -1 and 1.

### But what's an eigenvalue?

A quick review: Every square matrix $\mathbf{A}$ of dimension $n$ has $n$ associated eigenvalues $\left \{ \lambda_i \right \}_{i=1}^n$ such that each $\lambda_i$ solves the equation:

$$ \mathbf{A} \mathbf{v}_i = \lambda_i \mathbf{v}_i $$

for some eigenvector $\mathbf{v}_i$.

### How do we solve for eigenvalues?

Using computers! But we can get an idea of the solution in the following way:

$$
\begin{align}
\mathbf{A} \mathbf{v}_i &= \lambda_i \mathbf{v}_i\\
&\iff\\
\mathbf{A} \mathbf{v}_i &= \lambda_i \mathbf{I} \mathbf{v}_i\\
&\iff\\
\left ( \mathbf{A} - \lambda_i \mathbf{I}  \right ) \mathbf{v}_i &= \mathbf{0}
\end{align}
$$

The last step above, $\left ( \mathbf{A} - \lambda_i \mathbf{I}  \right ) \mathbf{v}_i = \mathbf{0}$, is a homogeneous system of equations. It will only have a non-trivial solution for $\mathbf{v}_i$ if the determinant of $\mathbf{A} - \lambda_i \mathbf{I}$ is equal to zero. Formally, we need that:

$$ \left | \mathbf{A} - \lambda_i \mathbf{I} \right | = 0$$

This is the equation we can use to characterize the solution for eigenvalues, and then, eigenvectors. To make it more concrete, let's look more closely at the 2$\times$2 case.

### The 2$\times$2 case

If our matrix is 2$\times$2, then our system is:

$$ \begin{align}\left | \begin{bmatrix}a_{11} & a_{12}\\ a_{21} & a_{22}  \end{bmatrix} - \begin{bmatrix}\lambda_i &0\\ 0 & \lambda_i \end{bmatrix} \right | &= 0 \\
&\iff\\
\left | \begin{bmatrix}a_{11}- \lambda_i & a_{12}\\ a_{21} & a_{22} - \lambda_i  \end{bmatrix}  \right | &= 0\\
&\iff\\
\lambda_i^2 - (a_{11} + a_{22}) \lambda_i + a_{11} a_{22}-a_{12} a_{21} &= 0 
\end{align}$$


This should give us 2 eigenvalues (real or complex). Once we have those, we can characterize the eigenvectors.

The important thing to remember about eigenvectors is that they are only unique up to a scaling factor. This means that within each vector, the ratios between entries must remain the same, but you can multiply the whole vector by any constant you like.

### Calculate eigenvalues/vectors with NumPy

The `numpy.linalg.eig()` function will do the trick!

Below, see an example with for the $\mathbf{A}$ which we defined earlier:

In [10]:
A = np.matrix([[1,2,3],
             [2,3,1],
             [2,1,3]
            ])

np.linalg.eig(A)

EigResult(eigenvalues=array([-1.,  6.,  2.]), eigenvectors=matrix([[-0.87038828,  0.57735027,  0.11547005],
        [ 0.34815531,  0.57735027, -0.80829038],
        [ 0.34815531,  0.57735027,  0.57735027]]))

### Quick exercise for eigenvalues and geometric sequences

Define some 3$\times$3 matrix whose largest eigenvalue has an absolute value greater than 1. Confirm the size of the largest eigenvalue using `numpy.linalg.det`. Confirm that the geometric sequence which consists of raising this matrix to higher and higher powers diverges.

Then, define some 3$\times$3 matrix whose largest eigenvalue is strictly bounded within $(-1,1)$. Confirm the size of the largest eigenvalue using `numpy.linalg.det`. Confirm that the geometric sequence which consists of raising this matrix to higher and higher powers converges.
